
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication4.Models
{

using System;
    using System.Collections.Generic;
    
public partial class comment
{

    public int comment_id { get; set; }

    public string text { get; set; }

    public System.DateTime created_at { get; set; }

    public int post_id { get; set; }

    public string user_id { get; set; }



    public virtual POST POST { get; set; }

    public virtual UserInfo UserInfo { get; set; }

}

}
