
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication4.Models
{

using System;
    using System.Collections.Generic;
    
public partial class comment
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public comment()
    {

        this.comment_like = new HashSet<comment_like>();

    }


    public int comment_id { get; set; }

    public string text { get; set; }

    public int Like_comment_num { get; set; }

    public int disLike_comment_num { get; set; }

    public System.TimeSpan created_at { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<comment_like> comment_like { get; set; }

    public virtual UserInfo UserInfo { get; set; }

    public virtual POST POST { get; set; }

}

}
