
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication4.Models
{

using System;
    using System.Collections.Generic;
    
public partial class like_post
{

    public int like_id { get; set; }

    public bool likeOrdislike { get; set; }



    public virtual POST POST { get; set; }

    public virtual UserInfo UserInfo { get; set; }

}

}
