

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication4.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Blog_MedicalEntities2 : DbContext
{
    public Blog_MedicalEntities2()
        : base("name=Blog_MedicalEntities2")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<UserInfo> UserInfoes { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<comment> comments { get; set; }

    public virtual DbSet<comment_like> comment_like { get; set; }

    public virtual DbSet<like_post> like_post { get; set; }

    public virtual DbSet<POST> POSTs { get; set; }

}

}

